### ISSUE TITLE
Include 'main.js' in gulp copy task

### ISSUE THREAD

**Issue by CJOchs** [ozone-development/center-ui#31]
Currently, the gulp copy task excludes all JS files, but the distribution, when deployed to NGINX or Apache HTTPD, requires assets/main.js.

Basically, change gulp/tasks/copy.js from:
```javascript
gulp.task('copy', function() {
    return gulp.src([
        'app/**/*',
        '!app/js',
        '!app/js/**/*',
        '!app/styles',
        '!app/styles/**/*']
        ).pipe(gulp.dest('dist'));
});
```

To (note second entry under gulp.src file listing)

```javascript
gulp.task('copy', function() {
    return gulp.src([
        'app/**/*',
        'app/js/main*.js
        '!app/js',
        '!app/js/**/*',
        '!app/styles',
        '!app/styles/**/*']
        ).pipe(gulp.dest('dist'));
});
```

Note: The "main*.js" was used because of a comment that a 'main-[hash].js' could be generated for cache-busting.

**Comment by nishp1** [comment]
main.js file gets copied by webpack, not by copy task.
