### ISSUE TITLE
Manually Clear Search Field

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/center-ui#44]
Bug from user:
After using the search field to discover and App in the Center, the user must actively remove the search argument.

Steps to reproduce:
1. With search file empty, click "Home"
2. Click to highlight only category "Business". Air Mail is displayed amoung the results
3. With search field emtpy click "Home"
4. in search field, enter "map" Chart Course is displayed amount the results
5. Click "Home"
6. Erase "map" from search field. Air Mail is displayed amount the results

**Comment by wski** [comment]
So what is the intended functionality? When is the desired time the search  should be automatically cleared?

**Comment by tonyalletag** [comment]
The tester expected the search variable when they clicked the "Home" link.  Please consult a UI/UX person to see what the intended functionality is.  If UI/UX  says it is working as designed we can close this bug

**Comment by sdeighan** [comment]
When "Map" is no longer actively filtering the results, the search term should clear. However, I think there's a bigger issue than just the search term not disappearing.

We will need to figure out what the system should do with the combination of a selected category and what the overall response should be from the system when "Home" is selected from a search results page. We will discuss it and get the rules worked out shortly.

**Comment by sdeighan** [comment]
We have discussed the issue and we are looking into the following changes:

1.) Clicking on Home will clear the search field
2.) Adding a search button to the search field
3.) Adding a clear button to the search field

**Comment by mparizernc** [comment]
All Browsers

Verified that the clear button clears the text and the home button sends you back to the original page.  The search button was decided to be not applicable.
