### ISSUE TITLE
HUD always displays "No Bookmarks"

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/center-ui#47]
The HUD page loads and displays "No Bookmarks" then it retrieves data and refreshes and displays any apps that are bookmarked.

Suggest changing initial load of HUD page to say "Loading Data"  then display apps that are bookmarked. If nothing is bookmarked display "No Bookmarks"

**Comment by nishp1** [comment]
This should be moved to hud-ui.

**Comment by tonyalletag** [comment]
Moved to HUD
