### ISSUE TITLE
Center has hardcoded url

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/center-ui#48]
Center attempts to connect to https:/raw.githubusercontent.com

This needs to be removed.

**Comment by rpokorny** [comment]
It appears that those URIs are in the mocked-out notification dropdown.  Once the real notifications are implemented they should be gone.

**Comment by nishp1** [comment]
It is already removed in notifications branch (in a local commit).

**Comment by mparizernc** [comment]
I scanned the app folder in Center and HUD and was unable to find the url in the ticket.
