### ISSUE TITLE
Center provides no content if there is an error condition

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/center-ui#50]
Center provides no content if there is an error condition. Something should be displayed to the users to notify them something went wrong.

**Comment by rpokorny** [comment]
If you are talking about the initial page load, it displays an `alert` box with the vague error message "Something went wrong. Try again!".  Not the best message or UI, but it does notify the user that there was an error.  Are you talking about a different, specific section of the UI that doesn't handle load errors?

**Comment by tonyalletag** [comment]
I think that message is fine and I thought this was fixed. I don't think we have that code in our production environment yet as it just displays a black screen with no message.  I will let clark close this one out if he thinks we have this  fixed.

**Comment by rpokorny** [comment]
> black screen

Are you sure you're talking about center and not HUD?  HUD I know does have this problem (it isn't blank though - it says you have no listings).  Center has had the alter messages for many months now.

**Comment by tonyalletag** [comment]
Yes this one is on Center. We saw this when the system was configured to use PKI but there were no interactions with the IAAS system.  A blank white screen with just the header and footer where displayed.  If this has been fix to display a simple error message to the user we can close this ticket.

**Comment by rpokorny** [comment]
Ah, ok.  We haven't really checked what it does in the case of a security plugin failure.  Might need to talk to you more offline about the configuration to get a good picture of what's going on.

**Comment by clarkjefcoat** [comment]
The complaint is not PKI specific.  What prompted this issue was that the message "Something went wrong. Try again!" is too vague (and once you press Ok, you are left with blank screen with only header and footer).  Ross, you had it correct in your initial comment.  Can you put a more informative message on the main page when there is an error?

**Comment by sdeighan** [comment]
We now have a set of more specific error messages and Ross is working on getting them into the platform. There are certain times when we will not know what caused an error and a generic message will be the only thing we can provide. However, wherever possible, errors should be more specific and actionable once this is implemented.

**Comment by mparizernc** [comment]
Test cases can be found https://www.owfgoss.org/confluence/display/DevInternal/Center+-+Log+in+Error+Page

I have tested against All Browsers for various error messages.
