### ISSUE TITLE
Marketplace Management - Update the Icons on the Administrative pages

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/center-ui#52]
The icons used in the tables' action buttons on the Marketplace Management pages are inconsistent with the rest of the application we should use the same icons on these pages as we do else where in the system.

* Categories Tab
* Stewards Tab
* Intents Tab
* Contact Types Tab
* Organizations Tab

**Comment by nishp1** [comment]
@sdeighan What should the icon classes be? 
Add: icon-square-plus?
Edit: fa-pencil?
Delete: ?

**Comment by sdeighan** [comment]
Add: icon-square-plus
Edit: fa-pencil
Delete: fa-trash-o

**Comment by mparizernc** [comment]
All Browsers 

Verified that the new icons have been used on the Marketplace Settings page.
