### ISSUE TITLE
Create/Edit Page - Change body to 3 column style

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/center-ui#56]
See mockups in OZF-678

**Comment by sdeighan** [comment]
![mp_createeditform](https://cloud.githubusercontent.com/assets/7987446/6304853/4364d502-b8f5-11e4-8c34-8ef536b62ff8.png)

**Comment by sdeighan** [comment]
UX Review completed. 3 column layout is working.

**Comment by mparizernc** [comment]
Verified that the three columns appear correct in all the browsers.
