### ISSUE TITLE
Create/Edit Page - Need "Delete" button

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/center-ui#69]
The form needs to have a delete button
![mp_createeditform_hoverdelete](https://cloud.githubusercontent.com/assets/7987446/6288503/8398ee82-b8e7-11e4-900f-56b94e2054c4.png)
![mp_createeditform](https://cloud.githubusercontent.com/assets/7987446/6288502/83950510-b8e7-11e4-8278-cab923261fad.png)

**Comment by mparizernc** [comment]
All browsers

There was a routing issues that was captured in a different ticket. I was able to delete from the Create/Edit page, My Listings, All Listings and Org Listings.
