### ISSUE TITLE
Search and Discovery Page - Search box needs a "clear" button

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/center-ui#72]
![mp_searchanddiscovery_searchterms](https://cloud.githubusercontent.com/assets/7987446/6292263/66f7e17c-b8f4-11e4-832e-c5e1a6d8449d.png)
![mp_searchanddiscovery](https://cloud.githubusercontent.com/assets/7987446/6292264/66f8b7b4-b8f4-11e4-8417-8311f740067a.png)

**Comment by wski** [comment]
Since the search searches automatically on each keypress what is the useful functionality of the search button?

**Comment by sdeighan** [comment]
None, if it continues to act that way. Part of this ticket is modifying how that acts. There was a question as to whether the bugs involving the typing would be solved or the work required for them would be reduced if we changed to the search button model. I left that choice to Nish and Ross; I'm not sure what they decided. If they choose to keep that functionality, we would no longer add a search button, only the clear.

**Comment by rpokorny** [comment]
I changed it so it waits to search until you stop typing for 500ms.  It does not require a search button.

**Comment by sdeighan** [comment]
Sounds good. Search button is now obsolete. I'll change the ticket title.

**Comment by mparizernc** [comment]
All Browsers

Verified that the clear button clears the text and the home button sends you back to the original page.  The search button was decided to be not applicable.
