### ISSUE TITLE
Sidebar height not 100%

### ISSUE THREAD

**Issue by wski** [ozone-development/center-ui#74]

**Comment by rpokorny** [comment]
I believe @sdeighan is already working on this

**Comment by sdeighan** [comment]
I was sidetracked by some other things, but yes, I am trying to deal with this one.

**Comment by sdeighan** [comment]
I was trying to deal with this. After investigation, I am not confident in my ability to replicate the original solution because my attempts have failed to date. Stephanie may be kind enough to help me out with it once her own tickets are complete.

**Comment by mparizernc** [comment]
The following places do not have the side bar height set to 100%:100: 
* Org Listings page
* Recent Activity
* My Listings page for non admin users

Also I believe you put a fix in for the filters not showing correctly but they are still showing incorrectly.

**Comment by rpokorny** [comment]
I will look again but I know for sure that those were already working (aside from possibly the Recent Activity page).

**Comment by rpokorny** [comment]
@mparizernc I am unable to reproduce the sidebar not working on the Org Listings and My Listings pages.  As far as Recent Activity goes, I'm not sure that's supposed to be the same kind of sidebar.  @sdeighan could you comment on that? Is the sidebar on the Recent Activity page supposed to expand to 100% height like the other ones?

**Comment by sdeighan** [comment]
@rpokorny It was the plan to have Recent Activity extend to 100% but I was having the most difficulty with getting it to obey.

**Comment by rpokorny** [comment]
To clarify, the sidebar will only be as tall as its own content or the content of the section next to it, whichever is greater.  I think @mparizernc was seeing it not expand when the content next to it is empty.  This is expected and I had previously confirmed with @sdeighan that that was OK.

**Comment by rpokorny** [comment]
@sdeighan do you need someone to fix that for this ticket?

**Comment by sdeighan** [comment]
@rpokorny @mparizernc The 100% height of content next-door is perfectly fine. For this ticket, it would be nice to have it on the Recent Activity page, but it is less critical than any TRR issues. So, it can be made a separate ticket if that would help.

**Comment by mparizernc** [comment]
So since I was unclear how this worked exactly what I was seeing was not an issue and therefore was working as expected.
