### ISSUE TITLE
Search and Discovery page - Selecting filters more then once does not work

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/center-ui#80]
When I land on the Search and Discovery page if I select a filter the filter is applied however I am no longer to unselect the filter or choose any other filters. 

Steps:
1) Choose a type Widget
2) Un-choose widget nothing happens to the listings
3) Choose a category nothing happens

Expected result: Unselecting a filter should remove it and applying other should filter the listings

**Comment by wski** [comment]
I noticed the indicators stopped working on Feb 12 hash a0cb4592662058744654314e2f7e5c908589088a not sure if that's just related to the styling issue or the entire thing.

**Comment by mparizernc** [comment]
All Browsers

Verified that I am able to select and unselect filters as well as selecting multiple filters at the same time.
