### ISSUE TITLE
Create/Edit Page - Selecting the Preview button causes the listing to not be able to be saved

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/center-ui#85]
I edited an existing listing, changed the version. The save button changed red with the floppy. I then selected the preview button when I did that the Save button changed to green and I was no longer able to save my changes.

Expected Result: the save button should have stayed red and allowed me to save my changes.

**Comment by nishp1** [comment]
Note: upgrade router 0.12.4 in ozp-react-commons and hud-ui when merging in master.

**Comment by mparizernc** [comment]
@nishp1 I have test the fix I guess once you are ready for me to look at the other upgrades let me know.

**Comment by mparizernc** [comment]
Verified that the HUD routing is working as expected.
