### ISSUE TITLE
Center logo overflows with some images

### ISSUE THREAD

**Issue by wski** [ozone-development/center-ui#88]

**Comment by mparizernc** [comment]
Please give more of a description and steps to reproduce.

**Comment by wski** [comment]
You have to change the source of the menu bar logo to the old appsmall one-- @sdeighan is just going to change the size of the image to fix this I believe.

**Comment by sdeighan** [comment]
I was testing it as you posted ^_^ It's attached in case anyone else needs it and I'm slacking it to you now
![appsmalllogomarketplace](https://cloud.githubusercontent.com/assets/7987446/6394930/ee82127c-bda2-11e4-986f-d46aaa336f6b.png)

**Comment by mparizernc** [comment]
Should we move this to done?
