### ISSUE TITLE
Listing management menu broken in FF

### ISSUE THREAD

**Issue by wski** [ozone-development/center-ui#89]

**Comment by mparizernc** [comment]
I assume this means the filters, correct?

**Comment by wski** [comment]
The issue can be seen here http://gyazo.com/5152ec8549b154df5085db6fac61a817

**Comment by mparizernc** [comment]
I was able to get this to happen by selecting filters sometimes it was messed up other times it looked fine. I saw this on the My Listings and All Listings tab.  I assume it happens on the Org Listings tab as well.

**Comment by nishp1** [comment]
resolved in branch `issue-89-listing-management-sidebar`. Once tested should be merged into master and deployed gh-pages.

**Comment by mparizernc** [comment]
All Browsers 

Verified that the width is set correctly and the filters are no longer shifting to the second line.
