### ISSUE TITLE
IE9 Display issues with font and icons for some users

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/center-ui#95]
For some users the icons and some fonts in center do not display.  We are working to get more details on this it could be firewalls, it could be the network... it could be they are using IE8.

I will update this issues as i get more details

**Comment by mparizernc** [comment]
This was because fonts were not being downloaded the solutions is to not use icons in fonts but to use svgs with sprites

**Comment by stephanieerin** [comment]
The svg-icon solution has been verified and is working on master.

**Comment by mparizernc** [comment]
All Browsers

All of the icons have been verified as well as making sure IE9 had downloading fonts disabled.
